spring:
  application:
    name: batch-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  batch:
    job:
      enabled: false

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

client:
  store-service:
    name: store-service
    url: http://localhost:8082
  notification-service:
    name: notification-service
    url: http://localhost:8084

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
    white-list:
      - /actuator/health
      - /actuator/prometheus
      - /error
      - /swagger-ui/**
      - /swagger-ui.html
      - /v3/api-docs/**
      - /v3/api-docs.yaml
      - /v3/api-docs.json
      - /api-docs/**
      - /swagger-resources/**
      - /webjars/**
      - /docs/**

rabbitmq:
  coupon-usage-stats-fcm-send:
    exchange: coupon.usage.stats.fcm.send.exchange
    queue: coupon.usage.stats.fcm.send.queue
    routing-key: coupon.usage.stats.fcm.send.routing.key